### ISSUE TITLE
link of the provided test case "buoyantCavity" 

### ISSUE THREAD

**Issue by fbob** [greole/owls#15]
Hi,

The ` generateExampleCase.sh` script make a link between the  `$FOAM_TUTORIALS/heatTransfer/buoyantSimpleFoam/buoyantCavity` and the "local"  `buoyantCavity` in the `examples` folder.

If the root of the OpenFOAM installation is located on the root of the filesystem it usually impossible to have write access to it and at execution time the run fail with a `permission denied` error.

May I suggest to simply make a `cp -a $FOAM_TUTORIALS/heatTransfer/buoyantSimpleFoam/buoyantCavity buoyantCavity` instead ?

**Comment by greole** [comment]
Good point! Thx.
