### ISSUE TITLE
Pandas version problem

### ISSUE THREAD

**Issue by meylone** [greole/owls#17]
Hi,

I tried to pip install the package but it complains not finding pandas 0.17.1. It seems having newer versions doesn't satisfy the requirement and `pip install pandas==0.17.1` does not find any matching distribution.

**Comment by greole** [comment]
Thanks for reporting. However, i cannot reproduce the reported behaviour. What pip/python version are you using? Anyways I have updated the pypi repository of owls, maybe that helps?

**Comment by GregorNeuber** [comment]
Version 0.6.4 only worked with `pip install pandas==0.13.1`
I do not know the behavior for later versions.
