### ISSUE TITLE
Python v3

### ISSUE THREAD

**Issue by fbob** [greole/owls#8]
It looks like owls is not Python 3 friendly  :  

```
File "build/bdist.linux-x86_64/egg/Owls/__init__.py", line 15
    print "Owls Version: " + __version__
                         ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.linux-x86_64/egg/Owls/mplinterface.py", line 128
    print e
          ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.linux-x86_64/egg/Owls/FoamFrame.py", line 196
    print "re-importing",
                       ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.linux-x86_64/egg/Owls/io.py", line 132
    print "writing %s : %s" % (time, fname)
                          ^
SyntaxError: invalid syntax
```

**Comment by greole** [comment]
I am currently working on the next release (v 0.7) of Owls which should be python v3.4 compatible. Try the 0.7 branch in the meanwhile .

**Comment by fbob** [comment]
Thank you very much for the info.
What a great project, and excellent work !

**Comment by fbob** [comment]
`version.py` is missing in owls-0.7

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    with open(version_py, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'Owls/version.py'
```

**Comment by greole** [comment]
As a quick fix just create an empty file 

     touch Owls/version.py

I'll push a bunch of commits, when i find the time.

**Comment by greole** [comment]
Ok the version.py should be generated automatically now. And I pushed a  number of other commits too. The version 0.7 (especially with python3.x) could be still a bit bumpy, so thanks a lot for testing it ;). If we could generate some more interest in Owls, people hopefully will help to write more tests and documentation.
